config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :phs
root "phs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ph.rb
class Ph < ApplicationRecord
  mount_uploader :file_location, PhImageUploader
  validates_presence_of :title, :date, :description, :file_location
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/phs_controller.rb
class PhsController < ApplicationController
  before_action :set_ph, :only => [:show, :edit, :update, :destroy]

def index
  @phs = Ph.all
end
def new
  @ph = Ph.new
end

def create
  @ph = Ph.new(ph_params)
  if @ph.save
  redirect_to phs_url
else
  render :action => :new
end
end

def update
  if @ph.update_attributes(ph_params)
  redirect_to ph_path(@ph)
else
  render :action => :edit
end
end

def destroy
  @ph.destroy

  redirect_to phs_url
end

private

def set_ph
  @ph = Ph.find(params[:id])
end

def ph_params
  params.require(:ph).permit(:title, :date, :description, :file_location)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/phs_helper.rb
module PhsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhAlbum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/phs/_form.html.erb
<% if @ph.errors.present? %>
<ul>
  <% @ph.errors.each do |error, message| %>
  <li> <%="#{error.capitalize} #{message}" %></li>
  <% end %>
</ul>
<% end %>

<div class="form container"
<%= form_for @ph do |f| %>
<div class="form-group">
<%= f.label :title, "Title" %>
<%= f.text_field :title, class:"form-control" %>
</div>
<div class="form-group">
<%= f.label :date, "Date" %>
<%= f.text_field :date, class:"form-control" %>
</div>
<div class="form-group">
<%= f.label :description %>
<%= f.text_field :description, class:"form-control" %>
</div>
<div class="form-group">
<%= f.label :file_location %>
<%= f.file_field :file_location %>
</div>
<%= f.submit %>
<% end %>

app/views/phs/edit.html.erb
<%= render :partial => "form" %>

app/views/phs/index.html.erb
<table class="table table-striped table-condensed">
 <% @phs.each do |ph| %>
   <tr>
     <td><%= ph.title %></td>
     <td><%= link_to 'Show', ph_path(ph) %></td>
     <td><%= link_to 'Edit', edit_ph_path(ph) %></td>
     <td><%= link_to 'Destroy', ph_path(ph), method: :delete, data:{ confirm: "Are you sure?" } %></td>
   </tr>
 <% end %>
</table>

<%= link_to 'New Ph', new_ph_path %>

app/views/phs/new.html.erb
<%= render :partial => "form" %>

app/views/phs/show.html.erb
<%= @ph.title %>
<%= @ph.date %>
<%= image_tag @ph.file_location.url, size: "140x140", class: "img-thumbnail" %>
<%= simple_format(@ph.description) %>

<p><%= link_to "Back to index", phs_path %></p>